data_path: ~/code/ml_exp_tracking_benchmark/places365_standard/
device: cuda:0
weight_dir: checkpoints
arch: vision_transformer
workers: 6
epochs: 7
start_epoch: 0
batch_size: 32
lr: 1e-4
momentum: 0.9
weight_decay: 1e-5
print_freq: 100
pretrained: True
feature_extract: False
num_classes: 365
dataset: places365

ml_track_framework: neptune

hydra:
  run:
    dir: exp_track/${now:%Y-%m-%d-%H-%M-%S}/log
tensorborad_log_dir:  exp_track/${now:%Y-%m-%d-%H-%M-%S}/tensorboard